# Arrays

Aarrays in Python are a compact way of collecting basic data types, all the entries in an array must be of the same data type. However, arrays are not all that popular in Python, unlike the other programming languages such as C++ or Java.

In [1]:
import array as arr
a = arr.array("I",[3,6,9,2,4,5,6,3,4,5,6,7,8,9])
type(a)

array.array

###### Insert Element

In [2]:
a.insert(1,100)
print(a)

array('I', [3, 100, 6, 9, 2, 4, 5, 6, 3, 4, 5, 6, 7, 8, 9])


In [3]:
a.append(500)
print(a)

array('I', [3, 100, 6, 9, 2, 4, 5, 6, 3, 4, 5, 6, 7, 8, 9, 500])


###### Remove element

In [4]:
a.remove(3)
print(a)

array('I', [100, 6, 9, 2, 4, 5, 6, 3, 4, 5, 6, 7, 8, 9, 500])


In [5]:
a.pop(3)
print(a)

array('I', [100, 6, 9, 4, 5, 6, 3, 4, 5, 6, 7, 8, 9, 500])


##### Accessing and slicing

In [6]:
a[10]

7

In [7]:
a[1:5]

array('I', [6, 9, 4, 5])

In [8]:
a[4:]

array('I', [5, 6, 3, 4, 5, 6, 7, 8, 9, 500])

In [9]:
a[:-3]

array('I', [100, 6, 9, 4, 5, 6, 3, 4, 5, 6, 7])

In [10]:
a[-4:-1]

array('I', [7, 8, 9])

##### Searching index of an element

In [11]:
a.index(100)

0

In [12]:
a.index(500)

13

-----------

### 2D Array

In [45]:
import numpy as np
aa = np.array([[1,2,4,5],[3,5,7,9],[2,4,6,7]], dtype = "i")
aa

array([[1, 2, 4, 5],
       [3, 5, 7, 9],
       [2, 4, 6, 7]], dtype=int32)

In [46]:
aa[0,0] = 100
print(aa)

[[100   2   4   5]
 [  3   5   7   9]
 [  2   4   6   7]]


In [48]:
aa[2:4,0:2]

array([[2, 4]], dtype=int32)

--------------